name: Checkout Code
on: [push, workflow_dispatch]
jobs:
  show-context-object:
    runs-on: windows-2019
    steps:
      - name: show context object
        run: echo "${{ toJSON(github) }}"
  download-code:
    runs-on: windows-2019
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      
  deploy:
    needs: download-code
    runs-on: windows-2019
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Download node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying....."
    
      
    
      
