name: Checkout Code
on: push
jobs:
  download-code:
    runs-on: windows-2019
    steps:
    - name: Download code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
      
    
      
